USE [master]
GO
ALTER DATABASE [AnimalCareDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
    EXEC [AnimalCareDB].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO
ALTER DATABASE [AnimalCareDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AnimalCareDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AnimalCareDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AnimalCareDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AnimalCareDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [AnimalCareDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AnimalCareDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AnimalCareDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AnimalCareDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AnimalCareDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AnimalCareDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AnimalCareDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AnimalCareDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AnimalCareDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AnimalCareDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AnimalCareDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AnimalCareDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AnimalCareDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AnimalCareDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AnimalCareDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AnimalCareDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AnimalCareDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AnimalCareDB] SET RECOVERY FULL 
GO
ALTER DATABASE [AnimalCareDB] SET  MULTI_USER 
GO
ALTER DATABASE [AnimalCareDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AnimalCareDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AnimalCareDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AnimalCareDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AnimalCareDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AnimalCareDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AnimalCareDB', N'ON'
GO
ALTER DATABASE [AnimalCareDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [AnimalCareDB] SET QUERY_STORE 
(
    OPERATION_MODE = READ_WRITE, 
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), 
    DATA_FLUSH_INTERVAL_SECONDS = 900, 
    INTERVAL_LENGTH_MINUTES = 60, 
    MAX_STORAGE_SIZE_MB = 1000, 
    QUERY_CAPTURE_MODE = AUTO, 
    SIZE_BASED_CLEANUP_MODE = AUTO, 
    MAX_PLANS_PER_QUERY = 200, 
    WAIT_STATS_CAPTURE_MODE = ON
)
GO